ERROR_TRAIN_NOT_FOUND = "ID TRAIN NOT FOUND"
ERROR_FILE_NOT_FOUND = "FileNotFoundError"
ERROR_FILE_CSV_NOT_FOUND = "File CSV NotFoundError"
ERROR_TASK_STATUS_BLOCKED = "TRAINING TASK MUSTN'T START BECAUSE IT HAS WAS STARTING OR COMPLETED"

ERROR_TASK_NOT_START = "TASK TRAINING IS FINISHED OR PENDING"

SUCCESSFULLY = "SUCCESSFULLY"

ERROR_REPORT_NOT_FOUND = "ERROR_REPORT_NOT_FOUND"
